"""empty message

Revision ID: 52e9324aab81
Revises: 2dc2d1b6cea5
Create Date: 2023-09-25 11:25:48.173450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e9324aab81'
down_revision = '2dc2d1b6cea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Enum('ELECTRONICS', 'CLOTHING', 'OTHER', 'HOME', 'BOOKS', 'SPORTS', name='categoryenum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
