"""empty message

Revision ID: 875b0aadc6e1
Revises: fc057684fccc
Create Date: 2023-10-22 19:44:11.079226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875b0aadc6e1'
down_revision = 'fc057684fccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_by', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('read_by')

    # ### end Alembic commands ###
